# Generated by Django 5.0.4 on 2024-06-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_asset_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asset_name', models.CharField(max_length=100)),
                ('Asset_type', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Item_code', models.CharField(max_length=100)),
                ('Assigned_To', models.CharField(max_length=100)),
                ('images', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
