# Generated by Django 5.0.4 on 2024-06-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0005_alter_asset_login_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Asset_Login',
        ),
    ]
